### ISSUE TITLE
Bug: Toggle Password Visibility Not Working.

### ISSUE THREAD

**Issue by rasel9t6** [milancommunity/Milan#1156]
### Description

Toggle password visibility not working on the **Sign up** and **Log in / Sign in**  page. As a result, users will not be able to understand or review whether their provided **password** and **Confirm password** is  incorrect or correct / match or mismatch.

### Proposed Solution

This might be a solution from **W3 Schools** Documentation. Bellow the Link
[W3 School Doc](https://www.w3schools.com/howto/howto_js_toggle_password.asp)

### Screenshots

![Screenshot 2023-10-28 231616](https://github.com/MilanCommunity/Milan/assets/116421413/e2fc1e3e-0e96-482a-b8d0-42040ab51ab1)
![Screenshot 2023-10-28 233258](https://github.com/MilanCommunity/Milan/assets/116421413/140c38ad-0085-45ab-9937-820b871bc86a)

### Browser 🥦

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by P-Jaswanth** [comment]
Hey, I would like to work on this. Could you please allocate this to me.

**Comment by Aryashakya** [comment]
I have tried it and it is working for me.
![image](https://github.com/MilanCommunity/Milan/assets/67620278/e7c50d1e-daf9-4a33-a269-a40a6c13981f)
![image](https://github.com/MilanCommunity/Milan/assets/67620278/ce4e1ba3-9bfc-4489-80a3-0d094c41030f)

**Comment by rasel9t6** [comment]
> I have tried it and it is working for me. ![image](https://user-images.githubusercontent.com/67620278/278875447-e7c50d1e-daf9-4a33-a269-a40a6c13981f.png) ![image](https://user-images.githubusercontent.com/67620278/278875453-ce4e1ba3-9bfc-4489-80a3-0d094c41030f.png)
It's not working for me.

**Comment by tamalCodes** [comment]
Hey @rasel9t6 , it is working fine for me (Chrome, Brave). I'm not sure if there's gonna be a problem in Mozilla, can you try clearing out all the cache and try once again ?

**Comment by MangeshGawas** [comment]
Hey, @rasel9t6 
Its an bug in mozilla firefox browser , I Fixed that bug.

**Comment by tamalCodes** [comment]
I see, would be great if you can make a PR 🚀

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by tamalCodes** [comment]
Do raise a PR, and remove the `package-lock.json` file from the changes too.
Make sure you read our docs on how to make a proper PR !
